global using PlanMe.Data;
global using PlanMe.Models;
global using PlanMe.User_Controls;
global using PlanMe.Views;
global using PlanMe.Controls;
global using MySql.Data.MySqlClient;
global using System.Text.RegularExpressions;
global using System.Data;
global using System.Timers;